name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - run: dotnet build source/Contact-Conversion-Wizard.sln --configuration Release --framework net40
    - run: cd source/bin/Release/ && dir
